enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1                    # amount of cores to use for parallel patching, if not set $(nproc) is used
compression-level = 9                # module zip compression level
remove-rv-integrations-checks = true # remove checks from the revanced integrations

patches-source = "inotia00/revanced-patches" # where to fetch patches bundle from. default: "revanced/revanced-patches"
cli-source = "inotia00/revanced-cli"             # where to fetch cli from. default: "j-hc/revanced-cli"
# options like cli-source can also set per app
rv-brand = "ReVanced Extended" # rebrand from 'ReVanced' to something different. default: "ReVanced"

patches-version = "latest" # 'latest', 'dev', or a version number. default: "latest"
cli-version = "latest"       # 'latest', 'dev', or a version number. default: "latest"

[Some-App]
app-name = "Youtube" # if set, release name becomes SomeApp instead of Some-App. default is same as table name, which is 'Some-App' here.
enabled = true       # whether to build the app. default: true
build-mode = "both"   # 'both', 'apk' or 'module'. default: apk

# 'auto' option gets the latest possible version supported by all the included patches
# 'latest' gets the latest stable without checking patches support. 'beta' gets the latest beta/alpha
# whitespace seperated list of patches to exclude. default: ""
version = "auto"     # 'auto', 'latest', 'beta' or a version number (e.g. '17.40.41'). default: auto

# optional args to be passed to cli. can be used to set patch options
# multiline strings in the config is supported
patcher-args = """\
  -App icon=youtube \
  -Change splash icons=false \
  -Restore old splash animation=true \
  """

excluded-patches = """\
  'Alternative thumbnails' \
  'Change live ring click action' \
  'Change start page' \
  'Custom shorts action buttons' \
  'Custom branding name for Youtube' \
  'Description components' \
  'Disable resuming Miniplayer on startup' \
  'GmsCore support' \
  'Miniplayer' \
  'Overlay buttons' \
  'Seekbar components' \
  'Shorts components' \
  'Themes' \
  'Translations for Youtube' \
  'Visual preferences icons for Youtube' \
  """

included-patches = "'Custom header for Youtube' 'Force hide player buttons background' 'MaterialYou' 'Return Youtube username' "                          # whitespace seperated list of non-default patches to include. default: ""
include-stock = true                                       # includes stock apk in the module. default: true
exclusive-patches = false                                  # exclude all patches by default. default: false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "RVX-Module"                       # magisk module prop name.
apkmirror-dpi = "360-480dpi"                               # used to select apk variant from apkmirror. default: nodpi
arch = "both"                                         # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all
riplib = true                                              # enables ripping x86 and x86_64 libs from apks with j-hc revanced cli. default: true
